/*============================================================================*\
 Compile country outputs generated by revamping/1. Calculations_v2.do

 Input per country:
 - ${dataout}/01-Cleaned-FIA-Indicators_<ISO3>.dta

 Output:
 - ${dataout}/01-Cleaned-FIA-Indicators_AllCountries.dta
\*============================================================================*/

if "$revamp_country_list"=="" {
	di as err "Missing revamp_country_list. Set it in trunk before calling this compiler."
	exit 198
}

local initialized 0
tempfile all_countries

foreach c of global revamp_country_list {
	local c_up = upper("`c'")
	local f = "${dataout}/01-Cleaned-FIA-Indicators_`c_up'.dta"
	capture confirm file "`f'"
	if _rc {
		di as err "Skipping missing country output: `f'"
		continue
	}

	use "`f'", clear
	if `initialized'==0 {
		save `all_countries', replace
		local initialized 1
	}
	else {
		append using `all_countries'
		save `all_countries', replace
	}
}

if `initialized'==0 {
	di as err "No country outputs were found to compile."
	exit 601
}

use `all_countries', clear

* Optional sanity check: records should be unique by full decomposition key
capture noisily isid INDICATOR_ID CATEGORY_ID INSTRUMENT_ID INCOME_ID POVERTY_LINE_ID PARTITION_VALUE_ID PENSION_ID country dataset

save "${dataout}/01-Cleaned-FIA-Indicators_AllCountries.dta", replace

di as txt "Compiled output saved: ${dataout}/01-Cleaned-FIA-Indicators_AllCountries.dta"
